# Generated by Django 4.0 on 2023-09-24 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('family', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('gender', models.IntegerField(choices=[('man', 'مرد'), ('woman', 'زن')], verbose_name='جنسیت')),
                ('profileImage', models.ImageField(null=True, upload_to='profileImages/', verbose_name='عکس')),
                ('credit', models.IntegerField(default=0, verbose_name='اعتبار')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='کاربری')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر',
            },
        ),
    ]
