# Generated by Django 4.0 on 2023-09-27 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='family',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='name',
        ),
    ]
