# Generated by Django 4.0 on 2023-09-20 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام کنسرت')),
                ('singer_name', models.CharField(max_length=100, verbose_name='نام خواننده')),
                ('length', models.IntegerField(verbose_name='مدت زمان کنسرت')),
                ('poster', models.ImageField(null=True, upload_to='concertImages/', verbose_name='عکس پوستر کنسرت')),
            ],
            options={
                'verbose_name': 'کنسرت',
                'verbose_name_plural': 'کنسرت',
            },
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(default='تهران - برج میلاد', max_length=500)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='profileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('man', 'مرد'), ('woman', 'زن')], max_length=10)),
                ('profileImage', models.ImageField(null=True, upload_to='profileImages/')),
            ],
        ),
        migrations.CreateModel(
            name='TimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDateTime', models.DateTimeField()),
                ('seats', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'فروش بلیط شروع شده است'), (2, 'فروش بلیط تمام شده است'), (3, 'فروش بلیط کنسل شده است'), (4, 'در حال فروش بلیط')])),
                ('concertModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketSales.concertmodel')),
                ('locationModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketSales.locationmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketName', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(null=True)),
                ('ticketImage', models.ImageField(null=True, upload_to='ticketImages/')),
                ('profileModel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketSales.profilemodel')),
                ('timeModel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketSales.timemodel')),
            ],
        ),
    ]
